### ISSUE TITLE
Quark doesn't work

### ISSUE THREAD

**Issue by rajiiji** [bkudler/WavesetTransformer-ForTrevorWishart#1]
Hello,
I added "ProbabilityDistributions.sc" file into the extension folder. then I tried to install Quark but it doesn't install the Waveset instrument.
Quarks.install("https://github.com/bkudler/WavesetTransformer-ForTrevorWishart")
is this right code ?
thanks.

**Comment by bkudler** [comment]
were you able to get the Quark installed?

**Comment by rajiiji** [comment]
Hi,
Yes! I found out I just needed Git to install Quark. Everything is working
well now.
Thank you for the great software! This is awesome! :)

2024년 1월 9일 (화) 오전 12:58, Ben Kudler ***@***.***>님이 작성:

**Comment by bkudler** [comment]
Glad you like it and glad it's working! Everyone seems to get confused by the installation step with the probability. The probability package is only really used in one small part of the software, so I just removed that part. The install is now a lot easier if you want to tell your friends.

What's your name and where do you live?? E-mail me at bkudler@gmail.com. It would be great to connect.
